chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:chatter_name>/', views.detail, name='detail'),
    path('<str:chatter_name>/results/', views.results, name='results'),
    path('<str:chatter_name>/vote/', views.vote, name='vote')
]

chatapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
import datetime

from django.db import models
from django.utils import timezone


class Chatter(models.Model):
    name = models.CharField(max_length=200)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def joined_recently(self):
        return self.date_joined >= timezone.now() - datetime.timedelta(days=1)


class Message(models.Model):
    chatter = models.ForeignKey(Chatter, on_delete=models.CASCADE)
    message = models.CharField(max_length=140)
    posted = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.message

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404

from .models import Chatter


def index(request):
    latest_chatter_list = Chatter.objects.order_by('-date_joined')[:10]
    context = {
        'latest_chatter_list': latest_chatter_list,
    }
    return render(request, 'chat/index.html', context)


def detail(request, chatter_name):
    chatter = get_object_or_404(Chatter, name=chatter_name)
    return render(request, 'chat/detail.html', {'chatter': chatter})


def results(request, chatter_name):
    return HttpResponse(f"These are the votes for {chatter_name.capitalize()}'s messages.")


def vote(request, chatter_name):
    return HttpResponse(f"You're voting on {chatter_name.capitalize()}'s messages.")

chat/templates/chat/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ chatter.name }}</h1>
<ul>
{% for message in chatter.message_set.all %}
    <li>{{ message.posted }} - <strong>{{ message.message }}</strong></li>
{% endfor %}
</ul>
</body>
</html>

chat/templates/chat/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_chatter_list %}
    <ul>
    {% for chatter in latest_chatter_list %}
        <li><a href="/chat/{{ chatter.name }}/">{{ chatter.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No chatters are available.</p>
{% endif %}
</body>
</html>